### PR TITLE
Symhash3

### PR DESCRIPTION
**Pull request by tommay**
Third time's a charm?
Having a Responder.symhash method was confusing. This makes a new SymHash class with a merge! method for folding a Hash into it. It's possibly easier to understand if you look at the three commits individually.

I've got some more changes in mind to make the query and body parsing a little easier to follow, but this wanted to be done first.

### CODE REVIEW

**Comment by kenichi** [comment]
i think this is good, what do you think of [this](https://github.com/kenichi/angelo/compare/tommay:symhash3...sh3) ?

**Comment by kenichi** [comment]
Since SymHash is really only used in params, is it going to need its own file and spec? Maybe [keeping it in the params ones](https://github.com/kenichi/angelo/compare/tommay:symhash3...sh4) makes it clearer?

**Comment by tommay** [comment]
Sure.  The idea behind pulling it out into its own file with its own spec
was that it's sort of a generic thing that could be dropped into another
project, but I'm ok with embedding it.  One of my versions had the
constructor taking an optional Hash argument, but I can't remember why I
wasn't happy with that.  Oh yeah . . . I didn't like regular Hashes being
passed to code outside of params_parser.rb so I went back to putting the
recursive stuff in a local method like your original code did.  But
embedding SymHash in params_parser.rb solves that "problem".

Tom

**Comment by kenichi** [comment]
cool, as you can tell, this is a bit tricky. luckily, we can always change it later :smiley_cat:

**Pull request merged**
